<a href="https://colab.research.google.com/github/jjegan2007-dev/-EDA-_LAB/blob/main/EXP4.2_28.07.2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer


new_data = {
    "Age": [30, 50, np.nan, 28, 35, np.nan, 40],
    "Salary": [70000, np.nan, 55000, 90000, 62000, 75000, np.nan],
    "Category": ["C", "A", "B", "C", np.nan, "A", "B"],
    "Experience": [5, np.nan, 10, 3, np.nan, 12, 7]
}
df = pd.DataFrame(new_data)

mean_imputer = SimpleImputer(strategy="mean")
df["Age_Mean"] = mean_imputer.fit_transform(df[["Age"]])


median_imputer = SimpleImputer(strategy="median")
df["Salary_Median"] = median_imputer.fit_transform(df[["Salary"]])

mode_imputer = SimpleImputer(strategy="most_frequent")
df["Category_Mode"] = mode_imputer.fit_transform(df[["Category"]]).ravel()
num_cols = ["Age", "Salary", "Experience"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
df["Experience_MICE"] = df_mice["Experience"]

print(df)

    Age   Salary Category  Experience  Age_Mean  Salary_Median Category_Mode  \
0  30.0  70000.0        C         5.0      30.0        70000.0             C
1  50.0      NaN        A         NaN      50.0        70000.0             A
2   NaN  55000.0        B        10.0      36.6        55000.0             B
3  28.0  90000.0        C         3.0      28.0        90000.0             C
4  35.0  62000.0      NaN         NaN      35.0        62000.0             A
5   NaN  75000.0        A        12.0      36.6        75000.0             A
6  40.0      NaN        B         7.0      40.0        70000.0             B

    Age_MICE   Salary_MICE  Experience_MICE
0  30.000000  70000.000000         5.000000
1  50.000000  28206.687011        11.642012
2  38.835483  55000.000000        10.000000
3  28.000000  90000.000000         3.000000
4  35.000000  62000.000000         8.097098
5  31.226104  75000.000000        12.000000
6  40.000000  53226.840148         7.000000

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [7]:

mean_imputer = SimpleImputer(strategy="mean")
df["Age_Mean"] = mean_imputer.fit_transform(df[["Age"]])
print("DataFrame after Mean Imputation for Age:")
display(df[['Age', 'Age_Mean']].head())

DataFrame after Mean Imputation for Age:

    Age  Age_Mean
0  30.0      30.0
1  50.0      50.0
2   NaN      36.6
3  28.0      28.0
4  35.0      35.0

In [6]:

median_imputer = SimpleImputer(strategy="median")
df["Salary_Median"] = median_imputer.fit_transform(df[["Salary"]])
print("DataFrame after Median Imputation for Salary:")
display(df[['Salary', 'Salary_Median']].head())

DataFrame after Median Imputation for Salary:

    Salary  Salary_Median
0  70000.0        70000.0
1      NaN        70000.0
2  55000.0        55000.0
3  90000.0        90000.0
4  62000.0        62000.0

In [5]:

mode_imputer = SimpleImputer(strategy="most_frequent")
df["Category_Mode"] = mode_imputer.fit_transform(df[["Category"]]).ravel()
print("DataFrame after Mode Imputation for Category:")
display(df[['Category', 'Category_Mode']].head())

DataFrame after Mode Imputation for Category:

  Category Category_Mode
0        C             C
1        A             A
2        B             B
3        C             C
4      NaN             A

In [3]:

num_cols = ["Age", "Salary", "Experience"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
df["Experience_MICE"] = df_mice["Experience"]
print("DataFrame after MICE Imputation:")
display(df[['Age', 'Age_MICE', 'Salary', 'Salary_MICE', 'Experience', 'Experience_MICE']].head())

DataFrame after MICE Imputation:

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

    Age   Age_MICE   Salary   Salary_MICE  Experience  Experience_MICE
0  30.0  30.000000  70000.0  70000.000000         5.0         5.000000
1  50.0  50.000000      NaN  28206.687011         NaN        11.642012
2   NaN  38.835483  55000.0  55000.000000        10.0        10.000000
3  28.0  28.000000  90000.0  90000.000000         3.0         3.000000
4  35.0  35.000000  62000.0  62000.000000         NaN         8.097098